site_name: Mkdocs Template Site
site_description: 'DESCRIPTION All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/mccreary-heitage/'
repo_url: 'https://github.com/dmccreary/mccreary-heitage'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Chapters:
    - Table of Contents: content/index.md
    - Introduction: content/01-introduction/index.md
    - Family History and Genealogy: content/02-family-history-and-genealogy/index.md
    - Timeline: content/03-timeline/index.md
    - Geography: content/04-geography/index.md
    - Education: content/05-education/index.md
    - Heritage Tourism: content/06-heritage-tourism/index.md
    - Culture and Traditions: content/07-culture-and-traditions/index.md
    - Research: content/08-research/index.md
    - Stories: content/09-stories/index.md
  - Applications & Tools:
    - List of Applications & Tools: sims/index.md
    - Timeline Viewer: sims/timeline/index.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md
  - License: license.md
  - Prompts:
    - prompts/index.md
    - prompts/personas.md
    - prompts/readme.md
    - prompts/site-layout.md

# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX